import type { DiagramType } from "./diagramTypes";

/** Human-readable labels for diagram type dropdowns (keys are Kroki path slugs). */
export const DIAGRAM_TYPE_LABELS: Record<DiagramType, string> = {
  blockdiag: "BlockDiag",
  bpmn: "BPMN",
  bytefield: "Bytefield",
  seqdiag: "SeqDiag",
  actdiag: "ActDiag",
  nwdiag: "NwDiag",
  packetdiag: "PacketDiag",
  rackdiag: "RackDiag",
  c4plantuml: "C4 with PlantUML",
  d2: "D2",
  dbml: "DBML",
  ditaa: "Ditaa",
  erd: "Erd",
  excalidraw: "Excalidraw",
  graphviz: "GraphViz",
  mermaid: "Mermaid",
  nomnoml: "Nomnoml",
  pikchr: "Pikchr",
  plantuml: "PlantUML",
  structurizr: "Structurizr",
  svgbob: "Svgbob",
  symbolator: "Symbolator",
  tikz: "TikZ",
  vega: "Vega",
  "vega-lite": "Vega-Lite",
  wavedrom: "WaveDrom",
  wireviz: "WireViz",
};
